export enum ProductCategory {
  COMPUTERS = 'COMPUTERS',
  PERIPHERALS = 'PERIPHERALS',
  PHONES = 'PHONES',
  TABLETS = 'TABLETS',
  ACCESSORIES = 'ACCESSORIES',
  STORAGE = 'STORAGE',
  GAMING = 'GAMING',
  AUDIO = 'AUDIO',
  SMART_HOME = 'SMART_HOME'
}